## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.

application_df = pd.read_csv("../Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
drop_col_df=application_df.drop(["EIN", "NAME"], axis='columns')
drop_col_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
drop_col_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
class_apps=drop_col_df['APPLICATION_TYPE'].value_counts()

In [5]:
application_types_to_replace=list(class_apps[class_apps< 700].index)

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_apps2=drop_col_df['CLASSIFICATION'].value_counts()
class_apps2
classification_types_to_replace=list(class_apps2[class_apps2< 700].index)
for app in application_types_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(app,"Other")
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_apps2[class_apps2 > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE

# Replace in dataframe
for cls in classification_types_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [10]:
application_df_dummy=pd.get_dummies(application_df)

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE

X = application_df_dummy.drop(["IS_SUCCESSFUL"], axis=1).values
y = application_df_dummy["IS_SUCCESSFUL"].values

In [13]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 80
hidden_nodes_layer3 = 80

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

#third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                1569040

 dense_1 (Dense)             (None, 80)                6480

 dense_2 (Dense)             (None, 80)                6480

 dense_3 (Dense)             (None, 1)                 81

=================================================================
Total params: 1,582,081
Trainable params: 1,582,081
Non-trainable params: 0
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 17s 16ms/step - loss: 0.4761 - accuracy: 0.7747
Epoch 2/100
804/804 [==============================] - 13s 16ms/step - loss: 0.1428 - accuracy: 0.9467
Epoch 3/100
804/804 [==============================] - 16s 19ms/step - loss: 0.0947 - accuracy: 0.9612
Epoch 4/100
804/804 [==============================] - 15s 18ms/step - loss: 0.0919 - accuracy: 0.9621
Epoch 5/100
804/804 [==============================] - 15s 19ms/step - loss: 0.0896 - accuracy: 0.9628
Epoch 6/100
804/804 [==============================] - 15s 19ms/step - loss: 0.0898 - accuracy: 0.9623
Epoch 7/100
804/804 [==============================] - 14s 18ms/step - loss: 0.0889 - accuracy: 0.9628
Epoch 8/100
804/804 [==============================] - 14s 18ms/step - loss: 0.0888 - accuracy: 0.9633
Epoch 9/100
804/804 [==============================] - 13s 16ms/step - loss: 0.0880 - accuracy: 0.9632
Epoch 10/100
804/804 [==============================] - 13s 16ms/step - loss: 0.0869 - accuracy: 0.9633
Epoch 11/100
804/804 [==============================] - 12s 14ms/step - loss: 0.0870 - accuracy: 0.9637
Epoch 12/100
804/804 [==============================] - 12s 15ms/step - loss: 0.0862 - accuracy: 0.9643
Epoch 13/100
804/804 [==============================] - 12s 15ms/step - loss: 0.0857 - accuracy: 0.9645
Epoch 14/100
804/804 [==============================] - 12s 14ms/step - loss: 0.0851 - accuracy: 0.9647
Epoch 15/100
804/804 [==============================] - 11s 14ms/step - loss: 0.0849 - accuracy: 0.9643
Epoch 16/100
804/804 [==============================] - 11s 13ms/step - loss: 0.0845 - accuracy: 0.9647
Epoch 17/100
804/804 [==============================] - 11s 13ms/step - loss: 0.0842 - accuracy: 0.9654
Epoch 18/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0837 - accuracy: 0.9658
Epoch 19/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0831 - accuracy: 0.9650
Epoch 20/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0827 - accuracy: 0.9659
Epoch 21/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0824 - accuracy: 0.9656
Epoch 22/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0819 - accuracy: 0.9661
Epoch 23/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0813 - accuracy: 0.9663
Epoch 24/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0809 - accuracy: 0.9661
Epoch 25/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0807 - accuracy: 0.9661
Epoch 26/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0801 - accuracy: 0.9663
Epoch 27/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0803 - accuracy: 0.9665
Epoch 28/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0793 - accuracy: 0.9671
Epoch 29/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0791 - accuracy: 0.9674
Epoch 30/100
804/804 [==============================] - 12s 15ms/step - loss: 0.0787 - accuracy: 0.9673
Epoch 31/100
804/804 [==============================] - 11s 14ms/step - loss: 0.0783 - accuracy: 0.9678
Epoch 32/100
804/804 [==============================] - 11s 13ms/step - loss: 0.0778 - accuracy: 0.9678
Epoch 33/100
804/804 [==============================] - 11s 13ms/step - loss: 0.0780 - accuracy: 0.9677
Epoch 34/100
804/804 [==============================] - 11s 14ms/step - loss: 0.0771 - accuracy: 0.9682
Epoch 35/100
804/804 [==============================] - 11s 14ms/step - loss: 0.0767 - accuracy: 0.9682
Epoch 36/100
804/804 [==============================] - 11s 13ms/step - loss: 0.0765 - accuracy: 0.9682
Epoch 37/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0758 - accuracy: 0.9683
Epoch 38/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0756 - accuracy: 0.9686
Epoch 39/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0759 - accuracy: 0.9686
Epoch 40/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0751 - accuracy: 0.9688
Epoch 41/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0765 - accuracy: 0.9687
Epoch 42/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0749 - accuracy: 0.9693
Epoch 43/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0743 - accuracy: 0.9697
Epoch 44/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0745 - accuracy: 0.9694
Epoch 45/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0744 - accuracy: 0.9692
Epoch 46/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0732 - accuracy: 0.9695
Epoch 47/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0735 - accuracy: 0.9698
Epoch 48/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0730 - accuracy: 0.9699
Epoch 49/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0734 - accuracy: 0.9697
Epoch 50/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0736 - accuracy: 0.9700
Epoch 51/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0728 - accuracy: 0.9697
Epoch 52/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0721 - accuracy: 0.9700
Epoch 53/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0720 - accuracy: 0.9702
Epoch 54/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0722 - accuracy: 0.9707
Epoch 55/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0716 - accuracy: 0.9706
Epoch 56/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0713 - accuracy: 0.9698
Epoch 57/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0716 - accuracy: 0.9702
Epoch 58/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0735 - accuracy: 0.9696
Epoch 59/100
804/804 [==============================] - 11s 13ms/step - loss: 0.0712 - accuracy: 0.9704
Epoch 60/100
804/804 [==============================] - 12s 15ms/step - loss: 0.0705 - accuracy: 0.9705
Epoch 61/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0704 - accuracy: 0.9712
Epoch 62/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0716 - accuracy: 0.9705
Epoch 63/100
804/804 [==============================] - 10s 13ms/step - loss: 0.0706 - accuracy: 0.9704
Epoch 64/100
804/804 [==============================] - 11s 14ms/step - loss: 0.0704 - accuracy: 0.9710
Epoch 65/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0696 - accuracy: 0.9713
Epoch 66/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0696 - accuracy: 0.9713
Epoch 67/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0700 - accuracy: 0.9707
Epoch 68/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0696 - accuracy: 0.9713
Epoch 69/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0702 - accuracy: 0.9710
Epoch 70/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0712 - accuracy: 0.9712
Epoch 71/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0689 - accuracy: 0.9716
Epoch 72/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0690 - accuracy: 0.9717
Epoch 73/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0690 - accuracy: 0.9717
Epoch 74/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0689 - accuracy: 0.9717
Epoch 75/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0690 - accuracy: 0.9720
Epoch 76/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0682 - accuracy: 0.9719
Epoch 77/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0682 - accuracy: 0.9715
Epoch 78/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0690 - accuracy: 0.9716
Epoch 79/100
804/804 [==============================] - 13s 16ms/step - loss: 0.0682 - accuracy: 0.9720
Epoch 80/100
804/804 [==============================] - 11s 14ms/step - loss: 0.0687 - accuracy: 0.9719
Epoch 81/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0681 - accuracy: 0.9717
Epoch 82/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0719 - accuracy: 0.9711
Epoch 83/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0680 - accuracy: 0.9718
Epoch 84/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0671 - accuracy: 0.9721
Epoch 85/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0675 - accuracy: 0.9719
Epoch 86/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0677 - accuracy: 0.9720
Epoch 87/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0674 - accuracy: 0.9719
Epoch 88/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0676 - accuracy: 0.9727
Epoch 89/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0670 - accuracy: 0.9722
Epoch 90/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0675 - accuracy: 0.9718
Epoch 91/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0669 - accuracy: 0.9723
Epoch 92/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0666 - accuracy: 0.9727
Epoch 93/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0675 - accuracy: 0.9725
Epoch 94/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0672 - accuracy: 0.9722
Epoch 95/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0664 - accuracy: 0.9721
Epoch 96/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0667 - accuracy: 0.9722
Epoch 97/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0661 - accuracy: 0.9727
Epoch 98/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0663 - accuracy: 0.9726
Epoch 99/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0673 - accuracy: 0.9725
Epoch 100/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0694 - accuracy: 0.9720

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.9719 - accuracy: 0.7336 - 1s/epoch - 5ms/step
Loss: 0.9719394445419312, Accuracy: 0.7336443066596985

In [1]:
nn.save("AlphabetSoupCharity_optimization9.h5")

NameError: name 'nn' is not defined